In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [ ]:
df = pd.read_csv("/content/Iris - Iris.csv.xls")

In [ ]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
df.tail()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [ ]:
df.shape

(150, 6)

In [ ]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
from sklearn.preprocessing import MinMaxScaler #fit() is used to learn and transform() is used to apply that learning

In [ ]:
 scaler=MinMaxScaler()

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [ ]:
df.drop("Id", axis=1, inplace=True, errors='ignore')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   SepalLengthCm  150 non-null    float64
 1   SepalWidthCm   150 non-null    float64
 2   PetalLengthCm  150 non-null    float64
 3   PetalWidthCm   150 non-null    float64
 4   Species        150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [ ]:
print(df)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   SepalLengthCm  150 non-null    float64
 1   SepalWidthCm   150 non-null    float64
 2   PetalLengthCm  150 non-null    float64
 3   PetalWidthCm   150 non-null    float64
 4   Species        150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [ ]:
print(df['Species'].value_counts())

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [ ]:
df['Species']=df['Species'].map({
   'Iris-setosa':0,
    'Iris-versicolor':1,
    'Iris-virginica':2})

In [ ]:
df['Species'] #glitch

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: Species, Length: 150, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le=LabelEncoder()

In [ ]:
le.fit(df['Species'])

LabelEncoder()

In [ ]:
print(le.fit(df['Species']))

LabelEncoder()

In [ ]:
print(le.classes_)

[0 1 2]

In [ ]:
df['Species']=le.transform(df['Species'])

In [ ]:
print(df['Species'])

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: Species, Length: 150, dtype: int64

In [ ]:
df.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0            5.1           3.5            1.4           0.2        0
1            4.9           3.0            1.4           0.2        0
2            4.7           3.2            1.3           0.2        0
3            4.6           3.1            1.5           0.2        0
4            5.0           3.6            1.4           0.2        0

In [ ]:
x=df[["SepalLengthCm","SepalWidthCm","PetalLengthCm","PetalWidthCm"]]
x=df.drop("Species",axis=1)

y=df["Species"]

In [ ]:
print(x.shape)

(150, 4)

In [ ]:
y.shape

(150,)

In [ ]:
a=df['Species']
print (a)

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: Species, Length: 150, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train ,x_test ,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=42)

In [ ]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(120, 4)
(30, 4)
(120,)
(30,)

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
scaler.fit(x_train)

MinMaxScaler()

In [ ]:
print(scaler.data_min_)
print(scaler.data_max_)

[4.3 2.  1.  0.1]
[7.7 4.4 6.7 2.5]

In [ ]:
print(x_train.min())
print(x_train.max())

SepalLengthCm    4.3
SepalWidthCm     2.0
PetalLengthCm    1.0
PetalWidthCm     0.1
dtype: float64
SepalLengthCm    7.7
SepalWidthCm     4.4
PetalLengthCm    6.7
PetalWidthCm     2.5
dtype: float64

In [ ]:
x_train=scaler.transform(x_train)

In [ ]:
x_train

array([[0.08823529, 0.66666667, 0.        , 0.04166667],
       [0.41176471, 1.        , 0.0877193 , 0.125     ],
       [0.70588235, 0.45833333, 0.59649123, 0.54166667],
       [0.14705882, 0.58333333, 0.10526316, 0.04166667],
       [0.02941176, 0.5       , 0.05263158, 0.04166667],
       [0.58823529, 0.20833333, 0.70175439, 0.75      ],
       [0.61764706, 0.5       , 0.61403509, 0.58333333],
       [0.26470588, 0.625     , 0.0877193 , 0.04166667],
       [0.20588235, 0.66666667, 0.07017544, 0.04166667],
       [0.26470588, 0.875     , 0.0877193 , 0.        ],
       [0.44117647, 0.29166667, 0.71929825, 0.75      ],
       [0.5       , 0.58333333, 0.61403509, 0.625     ],
       [0.70588235, 0.45833333, 0.64912281, 0.58333333],
       [0.32352941, 0.79166667, 0.05263158, 0.125     ],
       [0.32352941, 0.70833333, 0.0877193 , 0.04166667],
       [0.35294118, 0.16666667, 0.47368421, 0.375     ],
       [0.58823529, 0.33333333, 0.71929825, 0.58333333],
       [0.61764706, 0.45833333, 0.78947368, 0.70833333],
       [0.67647059, 0.41666667, 0.59649123, 0.54166667],
       [0.85294118, 0.66666667, 0.89473684, 1.        ],
       [0.41176471, 0.375     , 0.56140351, 0.5       ],
       [0.97058824, 0.41666667, 0.98245614, 0.83333333],
       [0.38235294, 0.41666667, 0.61403509, 0.58333333],
       [0.23529412, 0.625     , 0.07017544, 0.04166667],
       [1.        , 0.33333333, 1.        , 0.79166667],
       [0.44117647, 0.29166667, 0.54385965, 0.375     ],
       [0.26470588, 0.58333333, 0.07017544, 0.04166667],
       [0.20588235, 0.625     , 0.05263158, 0.08333333],
       [0.23529412, 0.75      , 0.15789474, 0.125     ],
       [0.20588235, 0.        , 0.43859649, 0.375     ],
       [0.58823529, 0.29166667, 0.68421053, 0.70833333],
       [0.14705882, 0.58333333, 0.15789474, 0.04166667],
       [0.20588235, 0.41666667, 0.10526316, 0.04166667],
       [0.23529412, 0.54166667, 0.12280702, 0.16666667],
       [0.38235294, 0.29166667, 0.56140351, 0.5       ],
       [0.23529412, 0.58333333, 0.0877193 , 0.04166667],
       [0.41176471, 0.41666667, 0.56140351, 0.45833333],
       [1.        , 0.75      , 1.        , 0.875     ],
       [0.08823529, 0.5       , 0.07017544, 0.04166667],
       [0.55882353, 0.375     , 0.57894737, 0.5       ],
       [0.41176471, 0.20833333, 0.70175439, 0.79166667],
       [0.35294118, 0.91666667, 0.07017544, 0.04166667],
       [0.5       , 0.41666667, 0.66666667, 0.70833333],
       [0.44117647, 0.29166667, 0.71929825, 0.75      ],
       [0.5       , 0.08333333, 0.52631579, 0.375     ],
       [0.32352941, 0.41666667, 0.61403509, 0.58333333],
       [0.55882353, 0.58333333, 0.77192982, 0.91666667],
       [0.35294118, 0.125     , 0.52631579, 0.5       ],
       [0.32352941, 0.79166667, 0.12280702, 0.125     ],
       [0.20588235, 0.125     , 0.40350877, 0.375     ],
       [0.61764706, 0.29166667, 0.75438596, 0.75      ],
       [0.20588235, 0.54166667, 0.07017544, 0.04166667],
       [0.20588235, 0.5       , 0.03508772, 0.04166667],
       [0.35294118, 0.16666667, 0.49122807, 0.41666667],
       [0.70588235, 0.41666667, 0.70175439, 0.66666667],
       [0.17647059, 0.45833333, 0.0877193 , 0.        ],
       [0.44117647, 0.33333333, 0.71929825, 0.95833333],
       [0.20588235, 0.58333333, 0.0877193 , 0.04166667],
       [0.20588235, 0.625     , 0.10526316, 0.20833333],
       [0.47058824, 0.5       , 0.66666667, 0.70833333],
       [0.23529412, 0.20833333, 0.35087719, 0.41666667],
       [0.76470588, 0.5       , 0.8245614 , 0.91666667],
       [0.5       , 0.29166667, 0.71929825, 0.625     ],
       [0.52941176, 0.25      , 0.80701754, 0.54166667],
       [1.        , 0.41666667, 0.89473684, 0.91666667],
       [0.35294118, 0.20833333, 0.52631579, 0.5       ],
       [0.02941176, 0.375     , 0.07017544, 0.04166667],
       [0.        , 0.41666667, 0.01754386, 0.        ],
       [0.5       , 0.08333333, 0.70175439, 0.58333333],
       [0.85294118, 0.5       , 0.87719298, 0.70833333],
       [0.08823529, 0.45833333, 0.0877193 , 0.04166667],
       [0.23529412, 0.625     , 0.07017544, 0.08333333],
       [0.02941176, 0.41666667, 0.05263158, 0.04166667],
       [0.58823529, 0.20833333, 0.68421053, 0.58333333],
       [0.58823529, 0.58333333, 0.80701754, 0.95833333],
       [0.08823529, 0.58333333, 0.07017544, 0.08333333],
       [0.73529412, 0.41666667, 0.78947368, 0.83333333],
       [0.58823529, 0.54166667, 0.87719298, 1.        ],
       [0.11764706, 0.5       , 0.05263158, 0.04166667],
       [0.52941176, 0.375     , 0.64912281, 0.54166667],
       [0.64705882, 0.33333333, 0.63157895, 0.58333333],
       [0.55882353, 0.33333333, 0.66666667, 0.70833333],
       [0.79411765, 0.5       , 0.64912281, 0.54166667],
       [0.61764706, 0.5       , 0.75438596, 0.91666667],
       [0.23529412, 0.75      , 0.10526316, 0.04166667],
       [0.76470588, 0.45833333, 0.77192982, 0.83333333],
       [0.47058824, 0.41666667, 0.56140351, 0.58333333],
       [0.64705882, 0.41666667, 0.73684211, 0.79166667],
       [0.41176471, 0.25      , 0.43859649, 0.375     ],
       [0.26470588, 0.29166667, 0.50877193, 0.54166667],
       [0.52941176, 0.41666667, 0.63157895, 0.54166667],
       [0.05882353, 0.125     , 0.05263158, 0.08333333],
       [0.67647059, 0.375     , 0.63157895, 0.5       ],
       [0.35294118, 0.25      , 0.59649123, 0.45833333],
       [0.29411765, 0.70833333, 0.0877193 , 0.04166667],
       [0.38235294, 0.41666667, 0.54385965, 0.5       ],
       [0.88235294, 0.375     , 0.92982456, 0.70833333],
       [0.70588235, 0.54166667, 0.8245614 , 0.83333333],
       [0.23529412, 0.70833333, 0.0877193 , 0.125     ],
       [0.17647059, 0.16666667, 0.40350877, 0.375     ],
       [0.70588235, 0.54166667, 0.8245614 , 1.        ],
       [0.85294118, 0.41666667, 0.84210526, 0.625     ],
       [0.17647059, 0.45833333, 0.0877193 , 0.        ],
       [0.70588235, 0.45833333, 0.80701754, 0.95833333],
       [0.17647059, 0.41666667, 0.07017544, 0.04166667],
       [0.76470588, 0.45833333, 0.68421053, 0.58333333],
       [0.91176471, 0.33333333, 0.89473684, 0.75      ],
       [0.58823529, 0.375     , 0.80701754, 0.70833333],
       [0.41176471, 0.33333333, 0.54385965, 0.5       ],
       [0.64705882, 0.41666667, 0.78947368, 0.70833333],
       [0.58823529, 0.125     , 0.59649123, 0.5       ],
       [0.61764706, 0.375     , 0.57894737, 0.5       ],
       [0.38235294, 0.33333333, 0.68421053, 0.79166667],
       [0.47058824, 0.41666667, 0.71929825, 0.70833333],
       [0.32352941, 0.58333333, 0.12280702, 0.04166667],
       [0.52941176, 0.33333333, 0.52631579, 0.5       ],
       [0.17647059, 0.20833333, 0.61403509, 0.66666667],
       [0.44117647, 0.83333333, 0.03508772, 0.04166667],
       [0.44117647, 0.25      , 0.52631579, 0.45833333],
       [0.82352941, 0.41666667, 0.85964912, 0.83333333]])

In [ ]:
x_test=scaler.transform(x_test)

In [ ]:
x_test

array([[0.52941176, 0.33333333, 0.64912281, 0.45833333],
       [0.41176471, 0.75      , 0.12280702, 0.08333333],
       [1.        , 0.25      , 1.03508772, 0.91666667],
       [0.5       , 0.375     , 0.61403509, 0.58333333],
       [0.73529412, 0.33333333, 0.66666667, 0.54166667],
       [0.32352941, 0.58333333, 0.0877193 , 0.125     ],
       [0.38235294, 0.375     , 0.45614035, 0.5       ],
       [0.76470588, 0.45833333, 0.71929825, 0.91666667],
       [0.55882353, 0.08333333, 0.61403509, 0.58333333],
       [0.44117647, 0.29166667, 0.50877193, 0.45833333],
       [0.64705882, 0.5       , 0.71929825, 0.79166667],
       [0.14705882, 0.41666667, 0.07017544, 0.        ],
       [0.35294118, 0.625     , 0.05263158, 0.04166667],
       [0.17647059, 0.45833333, 0.0877193 , 0.        ],
       [0.23529412, 0.75      , 0.0877193 , 0.08333333],
       [0.58823529, 0.54166667, 0.64912281, 0.625     ],
       [0.64705882, 0.41666667, 0.84210526, 0.875     ],
       [0.38235294, 0.20833333, 0.50877193, 0.41666667],
       [0.41176471, 0.33333333, 0.61403509, 0.5       ],
       [0.61764706, 0.33333333, 0.80701754, 0.875     ],
       [0.11764706, 0.5       , 0.10526316, 0.04166667],
       [0.52941176, 0.41666667, 0.68421053, 0.70833333],
       [0.20588235, 0.58333333, 0.10526316, 0.125     ],
       [0.61764706, 0.33333333, 0.80701754, 0.83333333],
       [1.05882353, 0.75      , 0.94736842, 0.79166667],
       [0.70588235, 0.41666667, 0.73684211, 0.91666667],
       [0.70588235, 0.20833333, 0.84210526, 0.70833333],
       [0.73529412, 0.5       , 0.85964912, 0.91666667],
       [0.14705882, 0.41666667, 0.07017544, 0.08333333],
       [0.14705882, 0.45833333, 0.10526316, 0.04166667]])

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
model=LogisticRegression()

In [ ]:
model.fit(x_train,y_train)

LogisticRegression()

In [ ]:
y_pred=model.predict(x_test)

In [ ]:
print(y_pred)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 2 2 1 1 2 0 2 0 2 2 2 2 2 0 0]

In [ ]:
le.inverse_transform(y_pred)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 2, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [ ]:
print(le.classes_)

[0 1 2]

In [ ]:
# #classification metrics
# tp(truepositive)
# tn(truenegative)
# fp(falsepositive)
# fn(falsenegative
# # all confussion metrix
# accuracy
# precision
# recall
# f1_score

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score , precision_score

In [ ]:
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[10  0  0]
 [ 0  8  1]
 [ 0  0 11]]

In [ ]:
ac=accuracy_score(y_test,y_pred)
print(ac)

0.9666666666666667